name = "kyc-gateway"
main = "worker.js"
compatibility_date = "2026-09-02"
account_id = "fd6f05d3bbca4cc5f175ca4f7154552b"

[[d1_databases]]
binding = "AUDIT_DB"
database_name = "bervashun-audit"
database_id = "f2fe6105-b552-42b4-a2ca-9d2a349861da"

[[kv_namespaces]]
binding = "KYC_SANCTIONS"
id = "203d064ff04b45d9b15a363aa18427be"

[[kv_namespaces]]
binding = "GATEWAY_AUTH"
id = "06af84f811b84abbb1d956b639d0cd07"

[vars]
ENVIRONMENT = "production"
